config/routes.rb
Rails.application.routes.draw do  

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :cursos
  resources :asignaturas
  resources :actividads,  :except => :show
  resources :noticias  
  resources :controls
  resources :temas
  resources :trabajocasas
  resources :actividads

  get '/trabajocasas/new/:c', to: 'trabajocasas#new', as: 'trabajocasas_new'
  get '/controls/new/:c', to: 'controls#new', as: 'controls_new'
  get '/trabajos/new/:c', to: 'trabajos#new', as: 'trabajos_new'
  get '/admin', to: 'admin#index', as: 'admin'  
  get '/actividades/:id', to: 'actividads#index', as: 'actividades_curso'

  
  get '/admin/temas', to: 'admin#temas', as: 'admintemas'
  get '/admin/actividades', to: 'admin#actividades', as: 'adminactividades'
  get '/admin/controles', to: 'admin#controles', as: 'admincontroles'
  get '/admin/trabajos', to: 'admin#trabajos', as: 'admintrabajos'
  get '/admin/noticias', to: 'admin#noticias', as: 'adminnoticias'

  post '/reload_trabajos', to: 'trabajocasas#reload_trabajos', as: 'reload_trabajos'
  post '/edit_tema', to: 'admin#render_temas', as: 'tema_edit'
  post '/edit_actividad', to: 'admin#render_actividades', as: 'actividad_edit'
  post '/edit_control', to: 'admin#render_control', as: 'control_edit'
  post '/edit_trabajo', to: 'admin#render_trabajo', as: 'trabajo_edit'  
  post '/edit_noticia', to: 'admin#render_noticia', as: 'noticia_edit'
  post '/delete_control', to: 'admin#deleteControl', as: 'control_delete'  
  post '/delete_actividad', to: 'admin#deleteActividad', as: 'actividad_delete'  
  post '/delete_trabajo', to: 'admin#deleteTrabajo', as: 'trabajo_delete' 
  post '/delete_tema', to: 'admin#deleteTema', as: 'tema_delete'  
  post '/delete_noticia', to: 'admin#deleteNoticia', as: 'noticia_delete'  
  
  post '/reload_links', to: 'actividads#reload_links', as: 'reloadLinks'
  post '/upload_image' => 'upload#upload_image', :as => :upload_image

  patch '/noticias', to: 'noticias#update', as: 'update_noticia'
end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
  
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  
  def show
    @curso = Curso.find(Asignatura.find(params[:id]).curso)
    @asignatura = Asignatura.find(params[:id])
    @temas = Tema.where("asignatura=?", params[:id])
  end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/show.html.erb
<% content_for :title do %><%=@asignatura.name%> de <%=@curso.name%><% end %>

<a href="<%=curso_path(Curso.find(@asignatura.curso))%>" class="badge badge-primary"><%=Curso.find(@asignatura.curso).name%></a>

<%= render partial: '/asignaturas/partials/menuAdmin' %>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4"><img class="" src="/images/<%=@asignatura.image%>" alt="Generic placeholder image" width="200" height="auto"> <%=@asignatura.name%> de <a href="<%=curso_path(@curso.id)%>"><%=@curso.name%></a></h1>
  <p class="lead">Encuentra aquí todos los enlaces de las actividades o ejercicios complementarios para tu aprendizaje.</p>
</div>


<p class="display-4 text-center">Temas</p>

<div class="card-deck" style="padding-bottom:5px">
<%@temas.each_with_index do |t, index|%>
  <div class="card">
    <img class="card-img-top" width="200" src="/images/temas/<%=t.imagen%>" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%=t.titulo%></h5>
      <p class="card-text"><%=sanitize t.descripcion%></p>  
    </div>
    <div class="card-footer">
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a class="btn btn-outline-info btn-sm" href="<%=tema_path(t.id)%>">Ver actividades</a>
          <button type="button" class="btn btn-sm btn-outline-info">Edit</button>
        </div>
      </div>     
    </div>
  </div>
  
  <%if (index+1)%4 == 0%>
    </div>
    <div class="card-deck" style="padding-bottom:5px">
  <%end%>
<%end%>
</div>