config/routes.rb
Rails.application.routes.draw do  

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :cursos
  resources :asignaturas
  resources :actividads,  :except => :show
  resources :noticias  
  resources :controls
  resources :temas
  resources :trabajocasas
  resources :actividads

  get '/trabajocasas/new/:c', to: 'trabajocasas#new', as: 'trabajocasas_new'
  get '/controls/new/:c', to: 'controls#new', as: 'controls_new'
  get '/trabajos/new/:c', to: 'trabajos#new', as: 'trabajos_new'
  get '/admin', to: 'admin#index', as: 'admin'  
  get '/actividades/:id', to: 'actividads#index', as: 'actividades_curso'

  
  get '/admin/temas', to: 'admin#temas', as: 'admintemas'
  get '/admin/actividades', to: 'admin#actividades', as: 'adminactividades'
  get '/admin/controles', to: 'admin#controles', as: 'admincontroles'
  get '/admin/trabajos', to: 'admin#trabajos', as: 'admintrabajos'
  get '/admin/noticias', to: 'admin#noticias', as: 'adminnoticias'

  post '/reload_trabajos', to: 'trabajocasas#reload_trabajos', as: 'reload_trabajos'
  post '/edit_tema', to: 'admin#render_temas', as: 'tema_edit'
  post '/edit_actividad', to: 'admin#render_actividades', as: 'actividad_edit'
  post '/edit_control', to: 'admin#render_control', as: 'control_edit'
  post '/edit_trabajo', to: 'admin#render_trabajo', as: 'trabajo_edit'  
  post '/edit_noticia', to: 'admin#render_noticia', as: 'noticia_edit'
  post '/delete_control', to: 'admin#deleteControl', as: 'control_delete'  
  post '/delete_actividad', to: 'admin#deleteActividad', as: 'actividad_delete'  
  post '/delete_trabajo', to: 'admin#deleteTrabajo', as: 'trabajo_delete' 
  post '/delete_tema', to: 'admin#deleteTema', as: 'tema_delete'  
  post '/delete_noticia', to: 'admin#deleteNoticia', as: 'noticia_delete'  
  
  post '/reload_links', to: 'actividads#reload_links', as: 'reloadLinks'
  post '/upload_image' => 'upload#upload_image', :as => :upload_image

  patch '/noticias', to: 'noticias#update', as: 'update_noticia'
end

app/views/admin/actividades.html.erb
<div class="row" >
	  	  
	<div class="col-md-2">
		<%= render partial: '/admin/partials/sidebar' %>
	</div>

<div class="col-md-10">

<h1 class="jumbotron-heading display-4">      
	Actividades
</h1>

<ul class="nav">	
	<li class="nav-item">			
		<a class="nav-link active" href="<%=new_actividad_path%>">
			<i class="fas fa-plus"></i> Crear nueva actividad
		</a>
	</li>		
</ul>

<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th scope="col">Titulo</th>
			<th scope="col">Descripcion</th>
			<th scope="col">Imagen</th>
			<th scope="col">Tema</th>
			<th scope="col">Curso</th>
			<th scope="col">Editar</th>
			<th scope="col">Eliminar</th>
		</tr>
	</thead>
	<tbody>

		<%@actividades.each do |t|%>
		<tr>
			<th scope="row"><%=t.titulo%></th>
			<td><%= t.descripcion[0..50]%>...</td>
			<td><%= t.imagen%></td>
			<td><a href="<%=tema_path(t.tema)%>"><%= Tema.find(t.tema).titulo%></a></td>
			<td></td>
			<td>
					<button type="button" class="btn btn-primary" data-toggle="modal" data-id="<%=t.id%>" data-target="#exampleModal">
							Editar
					</button>
			</td>
			<td>
				<button onclick="destroyControl(this);" data-id="<%=t.id%>"  data-mensaje="<%=t.titulo%>" type="button" class="btn btn-outline-danger">Eliminar</button>
			</td>
		</tr>
		<%end%>
	</tbody>
</table>
</div>>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edición de tema</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="actividad" class="modal-body">
        ...
      </div>      
    </div>
  </div>
</div>
  </div>
</div>

<div id="mQuestion" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger">¡Atención!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> ¿Desea borrar el contenido?</p>
				<p id="mContenido"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <div id="btnDelete"></div>
      </div>
    </div>
  </div>
</div>

<script>
$('#exampleModal').on('show.bs.modal', function (event) {

  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('id') // Extract info from data-* attributes

  edit_actividad(recipient);
})

function destroyControl(event){
	var button = $(event) // Button that triggered the modal
  var recipient = button.data('id') // Extract info from data-* attributes
	var mensaje = button.data('mensaje');

	$('#mContenido').html(mensaje);
	$('#btnDelete').html('<button type="button" onclick="delete_contenido('+ "'actividad'" + ', '+recipient+');" class="btn btn-danger">Borrar</button>');

	$('#mQuestion').modal('show');
}
</script>

app/views/admin/controles.html.erb
<div class="row" >
	  	  
	<div class="col-md-2">
		<%= render partial: '/admin/partials/sidebar' %>
	</div>

<div class="col-md-10">

<h1 class="jumbotron-heading display-4">       
	Controles
</h1>

<ul class="nav">	
	<li class="nav-item">			
		<a class="nav-link active" href="<%=controls_new_path(5)%>">
			<i class="fas fa-plus"></i> Crear nuevo control
		</a>
	</li>		
</ul>

<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th scope="col">Asignatura</th>
			<th scope="col">Fecha</th>
			<th scope="col">Descripcion</th>
			<th scope="col"></th>
			<th scope="col"></th>
		</tr>
	</thead>
	<tbody>

		<%@controles.each do |t|%>
			<tr>
				<th scope="row"><%= Asignatura.find(t.asignatura).name%></th>		
				<td ><%=t.fecha.strftime("%a, %d-%m-%y")%></td>
				<td><%= t.descripcion%></td>	
				<td>
						<button type="button" class="btn btn-primary" data-toggle="modal" data-id="<%=t.id%>" data-target="#exampleModal">
								Editar
						</button>
				</td>
				<td>
					<button onclick="destroyControl(this);" data-id="<%=t.id%>"  data-mensaje="<%=Asignatura.find(t.asignatura).name%>/<%=t.fecha.strftime("%d-%m-%y")%>" type="button" class="btn btn-outline-danger">Eliminar</button>
				</td>
			</tr>
		<%end%>
	</tbody>
</table>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edición de control</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
					<div id="control" class="modal-body">
						...
					</div>      
				</div>
			</div>
		</div>
	</div>
</div>

<div id="mQuestion" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger">¡Atención!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> ¿Desea borrar el contenido?</p>
				<p id="mContenido"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <div id="btnDelete"></div>
      </div>
    </div>
  </div>
</div>

<script>
$('#exampleModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('id') // Extract info from data-* attributes

  edit_control(recipient);
})

function destroyControl(event){
	var button = $(event) // Button that triggered the modal
  var recipient = button.data('id') // Extract info from data-* attributes
	var mensaje = button.data('mensaje');

	$('#mContenido').html(mensaje);
	$('#btnDelete').html('<button type="button" onclick="delete_contenido('+ "'control'" + ', '+recipient+');" class="btn btn-danger">Borrar</button>');

	$('#mQuestion').modal('show');
}
</script>

app/views/admin/index.html.erb
<%= render partial: '/admin/partials/sidebar' %>

app/views/admin/noticias.html.erb
<div class="row" >
	  	  
	<div class="col-md-2">
		<%= render partial: '/admin/partials/sidebar' %>
	</div>
<div class="col-md-10">
<h1 class="jumbotron-heading display-4">       
	Noticias
</h1>

<ul class="nav">	
	<li class="nav-item">			
		<a class="nav-link active" href="<%=new_noticia_path%>">
			<i class="fas fa-plus"></i> Crear nueva noticia
		</a>
	</li>		
</ul>

<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th scope="col">Titulo</th>
			<th scope="col">Contenido</th>
			<th scope="col">Imagen</th>
			<th scope="col">Asignatura</th>
			<th scope="col">Editar</th>
			<th scope="col">Eliminar</th>
		</tr>
	</thead>
	<tbody>

		<%@noticias.each do |t|%>
		<tr>
			<th scope="row"><%=t.titulo%></th>
			<td><%= t.contenido.split.size%> palabras</td>
			<td><%= t.imagen%></td>
			<td><%= t.resumen%></td>
			<td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-id="<%=t.id%>" data-target="#exampleModal">
                    Editar
                </button>
            </td>
			<td><button onclick="destroyControl(this)" data-contenido="noticia" data-id="<%=t.id%>"  data-mensaje="<%=t.titulo%>" type="button" class="btn btn-outline-danger">Eliminar</button></td>
		</tr>
		<%end%>
	</tbody>
</table>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edición de tema</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="noticia" class="modal-body">
        ...
      </div>      
    </div>
  </div>
</div>
  </div>
</div>

<div id="mQuestion" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger">¡Atención!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> ¿Desea borrar el contenido?</p>
				<p id="mContenido"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <div id="btnDelete"></div>
      </div>
    </div>
  </div>
</div>

<script>
$('#exampleModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('id') // Extract info from data-* attributes

  edit_noticia(recipient);
})

</script>

app/views/admin/temas.html.erb
<div class="row" >
	  	  
	<div class="col-md-2">
		<%= render partial: '/admin/partials/sidebar' %>
	</div>
<div class="col-md-10">
<h1 class="jumbotron-heading display-4">       
	Temas
</h1>

<ul class="nav">	
	<li class="nav-item">			
		<a class="nav-link active" href="<%=new_tema_path%>">
			<i class="fas fa-plus"></i> Crear nuevo tema
		</a>
	</li>		
</ul>

<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th scope="col">Titulo</th>
			<th scope="col">Descripcion</th>
			<th scope="col">Imagen</th>
			<th scope="col">Asignatura</th>
			<th scope="col">Curso</th>
			<th scope="col">Editar</th>
			<th scope="col">Eliminar</th>
		</tr>
	</thead>
	<tbody>

		<%@temas.each do |t|%>
		<tr>
			<th scope="row"><%=t.titulo%></th>
			<td><%= t.descripcion%></td>
			<td><%= t.imagen%></td>
			<td><%= Asignatura.find(t.asignatura).name%></td>
			<td><%= Curso.find(Asignatura.find(t.asignatura).curso).name%></td>
			<td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-id="<%=t.id%>" data-target="#exampleModal">
                    Editar
                </button>
            </td>
			<td><button onclick="destroyControl(this)" data-contenido="tema" data-id="<%=t.id%>"  data-mensaje="<%=t.titulo%>" type="button" class="btn btn-outline-danger">Eliminar</button></td>
		</tr>
		<%end%>
	</tbody>
</table>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edición de tema</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="tema" class="modal-body">
        ...
      </div>      
    </div>
  </div>
</div>
  </div>
</div>

<div id="mQuestion" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger">¡Atención!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> ¿Desea borrar el contenido?</p>
				<p id="mContenido"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <div id="btnDelete"></div>
      </div>
    </div>
  </div>
</div>

<script>
$('#exampleModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('id') // Extract info from data-* attributes

  edit_tema(recipient);
})

</script>

app/views/admin/trabajos.html.erb
<div class="row" >
	  	  
	<div class="col-md-2">
		<%= render partial: '/admin/partials/sidebar' %>
	</div>

<div class="col-md-10">

<h1 class="jumbotron-heading display-4">       
	Tareas de casa
</h1>

<ul class="nav">	
	<li class="nav-item">			
		<a class="nav-link active" href="<%=trabajocasas_new_path(5)%>">
			<i class="fas fa-plus"></i> Crear nueva tarea de casa
		</a>
	</li>		
</ul>

<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th scope="col">Titulo</th>
			<th scope="col">Descripcion</th>
			<th scope="col">Fecha</th>
			<th scope="col">Asignatura</th>
			<th scope="col">Editar</th>
			<th scope="col">Eliminar</th>
		</tr>
	</thead>
	<tbody>

		<%@trabajos.each do |t|%>
		<tr>
			<th scope="row"><%=t.titulo%></th>
			<td><%= t.descripcion%></td>
			<td><%= t.date.strftime("%d-%m-%y")%></td>
			<td><%=Asignatura.find(t.asignatura).name%></td>

			<td>
					<button type="button" class="btn btn-primary" data-toggle="modal" data-id="<%=t.id%>" data-target="#exampleModal">
							Editar
					</button>
			</td>
			<td>
				<button onclick="destroyControl(this);" data-id="<%=t.id%>" data-contenido="trabajo"  data-mensaje="<%=t.titulo%>" type="button" class="btn btn-outline-danger">Eliminar</button>
			</td>
		</tr>
		<%end%>
	</tbody>
</table>
</div>
<%=%>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edición de Trabajo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="trabajo" class="modal-body">
        ...
      </div>      
    </div>
  </div>
</div>
  </div>
</div>

<div id="mQuestion" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger">¡Atención!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> ¿Desea borrar el contenido?</p>
				<p id="mContenido"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <div id="btnDelete"></div>
      </div>
    </div>
  </div>
</div>

<script>
$('#exampleModal').on('show.bs.modal', function (event) {

  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('id') // Extract info from data-* attributes

  edit_trabajo(recipient);
})

</script>