config/routes.rb
Rails.application.routes.draw do  

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :cursos
  resources :asignaturas
  resources :actividads,  :except => :show
  resources :noticias  
  resources :controls
  resources :temas
  resources :trabajocasas
  resources :actividads

  get '/trabajocasas/new/:c', to: 'trabajocasas#new', as: 'trabajocasas_new'
  get '/controls/new/:c', to: 'controls#new', as: 'controls_new'
  get '/trabajos/new/:c', to: 'trabajos#new', as: 'trabajos_new'
  get '/admin', to: 'admin#index', as: 'admin'  
  get '/actividades/:id', to: 'actividads#index', as: 'actividades_curso'

  
  get '/admin/temas', to: 'admin#temas', as: 'admintemas'
  get '/admin/actividades', to: 'admin#actividades', as: 'adminactividades'
  get '/admin/controles', to: 'admin#controles', as: 'admincontroles'
  get '/admin/trabajos', to: 'admin#trabajos', as: 'admintrabajos'
  get '/admin/noticias', to: 'admin#noticias', as: 'adminnoticias'

  post '/reload_trabajos', to: 'trabajocasas#reload_trabajos', as: 'reload_trabajos'
  post '/edit_tema', to: 'admin#render_temas', as: 'tema_edit'
  post '/edit_actividad', to: 'admin#render_actividades', as: 'actividad_edit'
  post '/edit_control', to: 'admin#render_control', as: 'control_edit'
  post '/edit_trabajo', to: 'admin#render_trabajo', as: 'trabajo_edit'  
  post '/edit_noticia', to: 'admin#render_noticia', as: 'noticia_edit'
  post '/delete_control', to: 'admin#deleteControl', as: 'control_delete'  
  post '/delete_actividad', to: 'admin#deleteActividad', as: 'actividad_delete'  
  post '/delete_trabajo', to: 'admin#deleteTrabajo', as: 'trabajo_delete' 
  post '/delete_tema', to: 'admin#deleteTema', as: 'tema_delete'  
  post '/delete_noticia', to: 'admin#deleteNoticia', as: 'noticia_delete'  
  
  post '/reload_links', to: 'actividads#reload_links', as: 'reloadLinks'
  post '/upload_image' => 'upload#upload_image', :as => :upload_image

  patch '/noticias', to: 'noticias#update', as: 'update_noticia'
end

app/views/admin/partials/_editActividad.html.erb
<%= form_for @actividad do |f| %>
   <div class="form-group">
    <label for="">Título</label>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>

    <div class="form-group">
    <label for="">Imagen</label>
    <%= f.text_field :imagen, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <label for="">Temas</label>
    <%= f.select :tema, options_for_select(@temas.map{ |u| [u.titulo, u.id] }), {}, { :class => 'form-control' } %>   
  </div>

  
  <div class="form-group">
    <label for="">Link</label>
    <%= f.text_field :link, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Descripcion</label>
    <%= f.text_area :descripcion, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Contenido</label>
    <%= f.text_area :contenido, class: "form-control" %>
  </div>
    
    <%= f.submit "Guardar", :class => "btn btn-primary mb-2"%>
  <% end %>

  
 <script>
 tinymce.init({
  selector: 'textarea',
  height: 200,
  theme: 'modern',
  plugins: 'print preview fullpage autolink directionality fullscreen image link media template table hr pagebreak nonbreaking insertdatetime lists textcolor wordcount imagetools contextmenu colorpicker textpattern help',
  toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
  image_advtab: true,
  templates: [
    { title: 'Test template 1', content: 'Test 1' },
    { title: 'Test template 2', content: 'Test 2' }
  ],
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css'
  ],
  images_upload_handler: function (blobInfo, success, failure) {
    var xhr, formData;
    xhr = new XMLHttpRequest();
    xhr.withCredentials = false;
    xhr.open('POST', '/upload_image');
    xhr.onload = function() {
      var json;

      if (xhr.status != 200) {
        failure('HTTP Error: ' + xhr.status);
        return;
      }
      json = JSON.parse(xhr.responseText);

      if (!json || typeof json.location != 'string') {
        failure('Invalid JSON: ' + xhr.responseText);
        return;
      }
      success(json.location);
    };
    formData = new FormData();
    formData.append('file', blobInfo.blob(), fileName(blobInfo));
    xhr.send(formData);
  }
 });  
</script>

app/views/admin/partials/_editControl.html.erb
<%= form_for @control do |f| %>
  <div class="form-group">
    <label for="">Descripcion</label>
    <%= f.text_field :descripcion, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Fecha</label>
    
    <div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                  <%= f.text_field :fecha, class: "form-control" %>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                    format: 'YYYY-MM-DD',
                    minDate: '<%=DateTime.now.strftime("%Y-%m-%d")%>'
                });
            });
        </script>
    </div>
</div>
  </div>

  
  <div class="form-group">
    <label for="">Asignatura</label>
    <%= f.select :asignatura, options_for_select(@asignaturas.map{ |u| [u.name, u.id] }), {}, {:onchange=> "", :class => 'form-control' } %>   
  </div>
    

    <%= f.submit "Guardar", :class => "btn btn-danger mb-2"%>
  <% end %>

app/views/admin/partials/_editNoticia.html.erb
<%= form_for noticia, url: noticias_path do |f| %>
  <div class="form-group">
    <label for="">Título</label>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>

    <div class="form-group">
    <label for="">Resumen</label>
    <%= f.text_field :resumen, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Noticia</label>
    <%= f.text_area :contenido, class: "form-control tinymce" %>
  </div>

  <div class="form-group">
    <label for="">Imagen</label>
    <%= f.text_field :imagen, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <label for="">tags</label>
    <%= f.text_field :tags, class: "form-control" %>
  </div>

  <%=hidden_field(:noticias, :id, :value => noticia.id)%>
    
    <%= f.submit "Añadir noticia", :class => "btn btn-primary mb-2"%>
  <% end %>


 <script>
 tinymce.init({
  selector: 'textarea',
  height: 500,
  theme: 'modern',
  plugins: 'print preview fullpage autolink directionality fullscreen image link media template table hr pagebreak nonbreaking insertdatetime lists textcolor wordcount imagetools contextmenu colorpicker textpattern help',
  toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
  image_advtab: true,
  templates: [
    { title: 'Test template 1', content: 'Test 1' },
    { title: 'Test template 2', content: 'Test 2' }
  ],
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css'
  ],
  images_upload_handler: function (blobInfo, success, failure) {
    var xhr, formData;
    xhr = new XMLHttpRequest();
    xhr.withCredentials = false;
    xhr.open('POST', '/upload_image');
    xhr.onload = function() {
      var json;

      if (xhr.status != 200) {
        failure('HTTP Error: ' + xhr.status);
        return;
      }
      json = JSON.parse(xhr.responseText);

      if (!json || typeof json.location != 'string') {
        failure('Invalid JSON: ' + xhr.responseText);
        return;
      }
      success(json.location);
    };
    formData = new FormData();
    formData.append('file', blobInfo.blob(), fileName(blobInfo));
    xhr.send(formData);
  }
 });  
</script>
 

app/views/admin/partials/_editTema.html.erb
<%= form_for @tema do |f| %>
  <div class="form-group">
    <label for="">Título</label>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>

    <div class="form-group">
    <label for="">Imagen</label>
    <%= f.text_field :imagen, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Descripcion</label>
    <%= f.text_area :descripcion, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Asignatura</label>
    <%= f.select :asignatura, options_for_select(asignaturas.map{ |u| [u.name, u.id] }), {}, { :class => 'form-control' } %>   
  </div>
    
    <%= f.submit "Guardar", :class => "btn btn-primary mb-2"%>
  <% end %>

app/views/admin/partials/_editTrabajo.html.erb
<%= form_for trabajo do |f| %>
  <div class="form-group">
    <label for="">Título</label>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>

    <div class="form-group">
    <label for="">Fecha</label>
    <%= f.text_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Descripción</label>
    <%= f.text_area :descripcion, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="">Asignatura</label>
    <%= f.select :asignatura, options_for_select(asignaturas.map{ |u| [u.name, u.id] }), {}, { :class => 'form-control' } %>   
  </div>
    
    <%= f.submit "Guardar", :class => "btn btn-primary mb-2"%>
  <% end %>

app/views/admin/partials/_linksActividad.html.erb
<%Actividad.find(id).link.split(';').each_with_index do |l,i|%>
<a target="_blank" href="<%=l%>"><button   type="button" class="btn btn-info btn-lg btn-block">Actividad <%=i+1%></button></a>
<hr>
<%end%>

app/views/admin/partials/_sidebar.html.erb
<style>

/*
 * Sidebar
 */

.sidebar {
  position: relative;
  top: 0;
  bottom: 0;
  left: 0;
  z-index: 100; /* Behind the navbar */
  padding: 0px 0 0; /* Height of navbar */
  box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
}

.sidebar-sticky {
  position: relative;
  top: 0;
  height:60vh;
  padding-top: .5rem;
  overflow-x: hidden;
  overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
}

@supports ((position: -webkit-sticky) or (position: sticky)) {
  .sidebar-sticky {
    position: -webkit-sticky;
    position: sticky;
  }
}

.sidebar .nav-link {
  font-weight: 500;
  color: #333;
}

.sidebar .nav-link .feather {
  margin-right: 4px;
  color: #999;
}

.sidebar .nav-link.active {
  color: #007bff;
}

.sidebar .nav-link:hover .feather,
.sidebar .nav-link.active .feather {
  color: inherit;
}

.sidebar-heading {
  font-size: .75rem;
  text-transform: uppercase;
}
</style>


 <nav class=" d-none col-md-12 d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
    <ul class="nav flex-column list-inline">
       <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Administrador</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>        
        <li class="nav-item list-inline-item">
        <a class="nav-link" href="<%=admintemas_path%>">
            <span data-feather="file"></span>
            Temas
        </a>
        </li>
        <li class="nav-item list-inline-item">
        <a class="nav-link" href="<%=adminactividades_path%>">
            <span data-feather="shopping-cart"></span>
            Actividades
        </a>
        </li>
        <li class="nav-item list-inline-item">
        <a class="nav-link" href="<%=admincontroles_path%>">
            <span data-feather="users"></span>
            Controles
        </a>
        </li>       
        <li class="nav-item list-inline-item">
        <a class="nav-link" href="<%=admintrabajos_path%>">
            <span data-feather="users"></span>
            Trabajos para casa
        </a>
        </li>      
        <li class="nav-item list-inline-item">
        <a class="nav-link" href="<%=adminnoticias_path%>">
            <span data-feather="users"></span>
            Noticias
        </a>
        </li>              
    </ul>            
    </div>
</nav>

<nav class=" d-block d-sm-none bg-light">
    <ul class="nav nav-pills nav-fill">          
        <li class="nav-item ">
        <a class="nav-link" href="<%=admintemas_path%>">
            <span data-feather="file"></span>
            Temas
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="<%=adminactividades_path%>">
            <span data-feather="shopping-cart"></span>
            Actividades
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="<%=admincontroles_path%>">
            <span data-feather="users"></span>
            Controles
        </a>
        </li>       
        <li class="nav-item ">
        <a class="nav-link" href="<%=admintrabajos_path%>">
            <span data-feather="users"></span>
            Trabajos para casa
        </a>
        </li>      
        <li class="nav-item">
        <a class="nav-link" href="<%=adminnoticias_path%>">
            <span data-feather="users"></span>
            Noticias
        </a>
        </li>              
    </ul>  
</nav>