config/routes.rb
Rails.application.routes.draw do  

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :cursos
  resources :asignaturas
  resources :actividads,  :except => :show
  resources :noticias  
  resources :controls
  resources :temas
  resources :trabajocasas
  resources :actividads

  get '/trabajocasas/new/:c', to: 'trabajocasas#new', as: 'trabajocasas_new'
  get '/controls/new/:c', to: 'controls#new', as: 'controls_new'
  get '/trabajos/new/:c', to: 'trabajos#new', as: 'trabajos_new'
  get '/admin', to: 'admin#index', as: 'admin'  
  get '/actividades/:id', to: 'actividads#index', as: 'actividades_curso'

  
  get '/admin/temas', to: 'admin#temas', as: 'admintemas'
  get '/admin/actividades', to: 'admin#actividades', as: 'adminactividades'
  get '/admin/controles', to: 'admin#controles', as: 'admincontroles'
  get '/admin/trabajos', to: 'admin#trabajos', as: 'admintrabajos'
  get '/admin/noticias', to: 'admin#noticias', as: 'adminnoticias'

  post '/reload_trabajos', to: 'trabajocasas#reload_trabajos', as: 'reload_trabajos'
  post '/edit_tema', to: 'admin#render_temas', as: 'tema_edit'
  post '/edit_actividad', to: 'admin#render_actividades', as: 'actividad_edit'
  post '/edit_control', to: 'admin#render_control', as: 'control_edit'
  post '/edit_trabajo', to: 'admin#render_trabajo', as: 'trabajo_edit'  
  post '/edit_noticia', to: 'admin#render_noticia', as: 'noticia_edit'
  post '/delete_control', to: 'admin#deleteControl', as: 'control_delete'  
  post '/delete_actividad', to: 'admin#deleteActividad', as: 'actividad_delete'  
  post '/delete_trabajo', to: 'admin#deleteTrabajo', as: 'trabajo_delete' 
  post '/delete_tema', to: 'admin#deleteTema', as: 'tema_delete'  
  post '/delete_noticia', to: 'admin#deleteNoticia', as: 'noticia_delete'  
  
  post '/reload_links', to: 'actividads#reload_links', as: 'reloadLinks'
  post '/upload_image' => 'upload#upload_image', :as => :upload_image

  patch '/noticias', to: 'noticias#update', as: 'update_noticia'
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  
end

app/controllers/actividads_controller.rb
class ActividadsController < ApplicationController

  def index
    if params[:id].nil?
      @actividades = Actividad.all
    else
      @actividades = Actividad.joins("INNER JOIN temas ON temas.id=actividads.tema")
    .joins("INNER JOIN asignaturas ON asignaturas.id=temas.asignatura")
    .joins("INNER JOIN cursos ON cursos.id=asignaturas.curso")
    .where("asignaturas.curso=?", params[:id])
    end

    
  end
    
  def show   
    @actividad = Actividad.find(params[:id])
    
  end

  def create
    Actividad.create(:tema => params[:actividad][:tema], 
                        :descripcion => params[:actividad][:descripcion],
                        :titulo => params[:actividad][:titulo],
                        :imagen => params[:actividad][:imagen],
                        :link => params[:actividad][:link])

    flash[:success] = "Se ha creado la nueva actividad."                    
    redirect_to adminactividades_path
  end

  def update
    actividad = Actividad.find(params[:id])
    actividad.update(:tema => params[:actividad][:tema], 
      :descripcion => params[:actividad][:descripcion],
      :titulo => params[:actividad][:titulo],
      :imagen => params[:actividad][:imagen],
      :link => params[:actividad][:link])

    flash[:success] = "Se ha actualizado la actividad."
    
    redirect_to adminactividades_path
  end


  def new
    @actividad = Actividad.new
    @asignaturas = Asignatura.all
    @temas = Tema.all
  end

  def reload_links    
    respond_to do |format|
      format.html { render :partial => "admin/partials/linksActividad", locals: {id: params[:id] } }
    end
  end
end

app/views/actividads/partials/_actividades.html.erb
<div class="card-deck" style="padding-bottom:50px">
    <%@actividades.each_with_index do |t, index|%>
      <div class="card">
        <div class="" style="height:200px;background-image:url('/images/actividades/<%=t.imagen%>');background-size:contain" ></div>
        <div class="card-body">
          <h5 class="card-title"><%=t.titulo%></h5>
          <p class="card-text"><%=(strip_tags  t.descripcion)[0..100]%> ...</p>  
        </div>
        <div class="card-footer">
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-id="<%=t.id%>" data-target="#exampleModalLong">
                Ver actividades
              </button>          
              <a class="btn btn-outline-info btn-sm" href="<%=actividad_path(t.id)%>">Saber más</a>
            </div>
          </div>     
        </div>
      </div>
      
      <%if (index+1)%3 == 0%>
        </div>
        <div class="card-deck" style="padding-bottom:50px">
      <%end%>
    <%end%>
    </div>

app/views/actividads/partials/_menuAdmin.html.erb
<%if user_signed_in? && current_user.role == "admin"%>
	<ul class="nav">	
    <li class="nav-item">			
			<a class="nav-link active" href="<%=new_actividad_path%>">
				<i class="fas fa-plus"></i> Crear nueva actividad
			</a>
		</li>		
	</ul>
<%end%>